version: '3'
services:
  dev:
    image: arishoham/gw-dev
    container_name: "gw-dev-hot"
    ports:
      - "4000:4000"
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
volumes:
  node_modules: